apiVersion: v2
name: daywise
description: Personal planning mobile app backend
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

keywords:
  - daywise
  - planning
  - mobile-app
  - ai-assistant
  - household

maintainers:
  - name: Dave Altena
    email: dave@example.com

home: https://github.com/davealtena/daywise
sources:
  - https://github.com/davealtena/daywise